---
title: "visualize sampling weight distribution scans"
author: "Bob"
date: "5/27/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r sampling_probabilities}
score <- seq(0, 1, length=1000)
p <- dnorm(score, mean=0.5, sd=0.2)
plot(score, p, type='l')

```

```{r ends_of_roc_curve}

foo <- with(RESULTS[[1]][[1]]$roc, data.frame(sensitivities, specificities))
with(RESULTS[[1]][[1]]$roc, plot(sensitivities ~ specificities))
abline(h=0.5, col="red")
abline(v=foo[foo$sensitivities < 0.5,][1,'specificities'], col="red")
abline(h=0.25, col="blue")
abline(v=foo[foo$sensitivities < 0.25,][1,'specificities'], col="blue")
abline(h=0.75, col="darkgreen")
abline(v=foo[foo$sensitivities < 0.75,][1,'specificities'], col="darkgreen")
abline(h=0.90, col="blue")
abline(v=foo[foo$sensitivities < 0.90,][1,'specificities'], col="blue")

```

```{r}

RESULTS <- readRDS(file="RESULTS.Rds")
PARAMETER_TABLE <- readRDS("PARAMETER_TABLE.Rds")

PARAMETER_TABLE$final_auc <- sapply(RESULTS, function(res) {
  final <- res[[length(res)]]
  as.numeric(auc(final$roc)) # auc_vec <- auc(res$roc); auc_vec[length(auc_vec)]
})


library(ggplot2)
g <- PARAMETER_TABLE %>% ggplot(aes(x=mu, y=final_auc)) + geom_point() + 
  geom_smooth(span=0.5)
# , col=factor(seed)


mu_vs_mean_auc <- PARAMETER_TABLE %>% group_by(mu) %>%
  summarize(mean_auc=mean(final_auc))

g + geom_point(data=mu_vs_mean_auc, mapping=aes(x=mu, y=mean_auc), col="red", size=2)

plot_parameter_set_results <- function(i){
  parameters <- PARAMETER_TABLE[i,]
  res <- RESULTS[[i]]
  plot_roc_history(res[[1]], res[2:length(res)], 
                   main=sprintf("seed=%d, mu=%0.2f, sigma=%0.2f", parameters$seed, parameters$mu, parameters$sigma))
}


```

To Do:

  * `run_random_sample_learning_curve` still uses rx functions
  * compute lift by decile (lift_decile01, etc)