---
title: "Wiki Deox Data set"
output: html_notebook
---

```{r setup}
library(tidyverse)

```
## Import data

The sample data comes from the [Wiki Detox](https://meta.m.wikimedia.org/wiki/Research:Detox/Data_Release) datasets.

```{r load_data}

DATA_DIR <- "e:/ml_data/cyberbullying/wiki_detox"

data_files <- DATA_DIR %>% list.dirs %>% list.files(pattern="*.tsv", full.names=TRUE)
names(data_files) <- data_files %>% strsplit("/") %>% map_chr(last) %>% gsub(".tsv", "", ., fixed=TRUE)

# gsub('NEWLINE_TOKEN', '\\n', .)
data_sets <- lapply(data_files, read_tsv)
```

```{r preliminary_exploration}

lapply(data_sets, dim)
lapply(data_sets, names)
tox_types <- c("attack", "aggression", "toxicity")

with(data_sets$aggression_annotation, table(aggression, aggression_score))

with(data_sets$toxicity_annotation, table(toxicity, toxicity_score))

attack_cols <- data_sets$attack_annotations %>% names %>% grep('attack', ., value=TRUE)
data_sets$attack_annotations %>% select(attack_cols) %>% colSums

data_sets$attack_annotations %>% filter(attack==1) %>% head(n=20)

# do attack and aggression have the same comments?
with(data_sets, intersect(attack_annotations$rev_id, aggression_annotations$rev_id)) %>% length

with(data_sets, all.equal(aggression_annotated_comments$comment, attack_annotated_comments$comment))
# TRUE

# are toxicity annotations on different comments than aggression/attack?
with(data_sets, intersect(attack_annotations$rev_id, toxicity_annotations$rev_id)) %>% length

# # Common subset of annotations
# common_rev_ids <- with(data_sets, intersect(attack_annotations$rev_id, toxicity_annotations$rev_id))
# 
# common_annotated_comments <- data_sets$aggression_annotated_comments %>% 
#   filter(rev_id %in% common_rev_ids) %>% 
#   select(rev_id, comment)
# 
# all.equal(common_annotated_comments$comment, data_sets$toxicity_annotated_comments %>% filter(rev_id %in% common_rev_ids) %>% "[["('comment'))
# 
# which ((common_annotated_comments$comment != data_sets$toxicity_annotated_comments %>% filter(rev_id %in% common_rev_ids) %>% "[["('comment'))) -> differences

has_rev_id <- sapply(data_sets, function(tbl) "rev_id" %in% names(tbl))

common_rev_ids <- data_sets[has_rev_id] %>% lapply("[[", 'rev_id') %>% purrr::reduce(intersect)

common_comments <- data_sets$aggression_annotated_comments %>% 
  filter(rev_id %in% common_rev_ids) %>% 
  select(rev_id, comment)
```

### Aggregate labels

```{r aggregate_labels}

attack_aggregated <- data_sets$attack_annotations %>%
  group_by(rev_id) %>%
  summarize(count=n(), avg_attack=mean(attack)) %>% 
  mutate(is_attack = avg_attack >= 0.5)

aggression_aggregated <- data_sets$aggression_annotations %>%
  group_by(rev_id) %>%
  summarize(count=n(), avg_aggression=mean(aggression_score)) %>% 
  mutate(is_aggression = avg_aggression < -0.75)

toxicity_aggregated <- data_sets$toxicity_annotations %>%
  group_by(rev_id) %>%
  summarize(count=n(), avg_toxicity=mean(toxicity_score)) %>% 
  mutate(is_toxicity = avg_toxicity < -0.5)

hist(attack_aggregated$avg_attack)
hist(aggression_aggregated$avg_aggression, breaks=30)
hist(toxicity_aggregated$avg_toxicity)

```

```{r join_and_save_data}
attack_data <- data_sets$attack_annotated_comments %>% inner_join(attack_aggregated, by="rev_id")
aggression_data <- data_sets$aggression_annotated_comments %>% inner_join(aggression_aggregated, by="rev_id")
toxicity_data <- data_sets$toxicity_annotated_comments %>% inner_join(toxicity_aggregated, by="rev_id")

saveRDS(attack_data, "attack_data.Rds")
saveRDS(aggression_data, "aggression_data.Rds")
saveRDS(toxicity_data, "toxicity_data.Rds")

# labeled_comments <- with(data_sets, common_comments %>% 
#   left_join(attack_annotations) %>%
#   left_join(aggression_annotations) %>%
#   left_join(toxicity_annotations))
# 
# saveRDS(labeled_comments, "wiki_labeled_comments.Rds")
## fill in NA values? 2157 complete cases.

```


```{r differences_in_annotation_comments}
foo <- tibble(common=common_annotated_comments$comment,toxicity= data_sets$toxicity_annotated_comments %>% filter(rev_id %in% common_rev_ids) %>% "[["('comment'))
foo[which(foo$common != foo$toxicity),] %>% as.data.frame-> different
```

# Fit logistic regression models

`aggression_score` goes from -3 to 3, with -3 being the most aggressive.

```{r logistic_regression}

labeled_comments <- readRDS("labeled_comments.Rds")

in_training <- sample(c(TRUE, FALSE), nrow(labeled_comments), replace=TRUE, prob=c(3/4, 1/4))
TRAINING_SET <- labeled_comments[in_training,]
TEST_SET <- labeled_comments[!in_training,]

fit_model <- function(outcome, training_data, L1=1, L2=1, N_GRAMS=2){
  form <- paste(outcome, "comment_features", sep=' ~') %>% as.formula
  rxLogisticRegression(form, 
                       data=training_data, 
                       mlTransforms=list(
                        featurizeText(vars=c(comment_features = "comment"), 
                                      wordFeatureExtractor=ngramCount(ngramLength=N_GRAMS),
                                      keepPunctuations = FALSE,
                                      keepNumbers = FALSE)
                      ), 
                      l1Weight=L1, l2Weight=L2, 
                      type="binary",
                      verbose=0, reportProgress=0)
}

fit_outcome_model <- function(outcome, ...){
  fit_model(outcome, training_data=TRAINING_SET %>% filter(!is.na(outcome)), ...)
}

outcomes <- c("attack", "aggression", "toxicity")
names(outcomes) <- outcomes

models_L1 <- lapply(outcomes, fit_outcome_model, L1=1, L2=1, N_GRAMS=2)
models_L05 <- lapply(outcomes, fit_outcome_model, L1=0.5, L2=0.5, N_GRAMS=2)

saveRDS(models_L1, "models_L1.Rds")
saveRDS(models_L05, "models_L05.Rds")
```

```{r calculate_roc}
models_L1 <- readRDS("models_L1.Rds")
models_L05 <- readRDS("models_L05.Rds")

models_L1 %>% lapply(function(fit) length(coef(fit)))
models_L05 %>% lapply(function(fit) length(coef(fit)))

```


```{r scraps}
pred_lr_attack <- rxPredict(fit_lr_attack, data=test_set, extraVarsToWrite="attack")

roc <- rxRoc("attack", "Probability.1", data=pred_lr_attack, numBreaks=100)
plot(roc)
roc %>% ggplot(aes(x=(1 - specificity), y=sensitivity)) + 
  geom_line() + 
  geom_abline(slope=1, intercept=0, linetype="dotted")

calculate_auc <- function(roc){
  with(roc, sum(sensitivity * c(0,diff(specificity))) - sum(diff(sensitivity) * diff(specificity))/2)
}

with(roc, plot(1 - specificity, sensitivity, type='b'))

tidy_auc <- function(roc){
  roc %>% 
    mutate(diffsens=c(diff(sensitivity),0), cumspec=cumsum(specificity), diffspec=c(diff(specificity),0)) %>%
    summarize(auc=sum((sensitivity + diffsens/2) * diffspec))
}

```

